name: Test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Build & Test on ${{ matrix.code-target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            code-target: win32-x64

          - os: windows-11-arm
            target: aarch64-pc-windows-msvc
            code-target: win32-arm64

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            code-target: linux-x64

          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            code-target: linux-arm64

          - os: macos-26-intel
            target: x86_64-apple-darwin
            code-target: darwin-x64

          - os: macos-latest
            target: aarch64-apple-darwin
            code-target: darwin-arm64

    steps:
      - name: Configure git line endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/actions/setup
        with:
          key: test-${{ matrix.target }}

      - name: Test
        run: cargo test --locked --all-features

  fmt:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/actions/setup
        with:
          components: rustfmt

      - name: Fmt
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/actions/setup
        with:
          components: clippy

      - name: Clippy
        run: RUSTFLAGS="-Dwarnings" cargo clippy --locked --all-features --all-targets

  docs:
    name: Check Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Docs
        run: RUSTDOCFLAGS="-Dwarnings" cargo doc --locked --all-features --no-deps

  publish-dryrun:
    name: Publish Dry Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/actions/setup
        with:
          key: publish-dryrun

      - name: Dry run publish
        run: cargo publish --locked --dry-run
